name: CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
    
    - name: Create bin directory
      run: mkdir -p bin
    
    - name: Compile Java files
      run: javac -d bin src/*.java
    
    - name: Verify compilation
      run: |
        cd bin
        ls -la *.class
        echo "Compilation successful - all class files generated"
    
    - name: Create JAR file
      run: |
        cd bin
        jar cfe ../uno-game-engine.jar GameDriver *.class
    
    - name: Upload JAR artifact
      uses: actions/upload-artifact@v4
      with:
        name: uno-game-engine
        path: uno-game-engine.jar

  release:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Download artifact
      uses: actions/download-artifact@v4
      with:
        name: uno-game-engine
    
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: v${{ github.run_number }}
        name: Release v${{ github.run_number }}
        files: uno-game-engine.jar
        token: ${{ secrets.GITHUB_TOKEN }}